# Generated by Django 4.1.5 on 2023-01-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
